# Generated by Django 4.0.2 on 2022-02-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_manager_base', '0002_alter_customusermodel_localization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='photo',
            field=models.FileField(upload_to='products/'),
        ),
    ]
