# Generated by Django 4.0.2 on 2022-02-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_manager_base', '0004_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='photo',
            field=models.FileField(null=True, upload_to='products/'),
        ),
    ]
