# Generated by Django 4.0.2 on 2022-02-13 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_manager_base', '0005_alter_productmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationoftransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default=('PENDING', 'Pending'), max_length=15),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='warehouse_manager_base.productsetmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
