# Generated by Django 4.0.2 on 2022-05-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_manager_base', '0008_alter_productmodel_localization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='product_set',
        ),
        migrations.DeleteModel(
            name='ProductSetModel',
        ),
    ]
