# Generated by Django 4.0.2 on 2022-05-31 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_manager_base', '0009_remove_categorymodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationoftransfer',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='confirmations', to='warehouse_manager_base.productmodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
