# Generated by Django 4.0.2 on 2022-05-31 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_manager_base', '0011_alter_confirmationoftransfer_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationoftransfer',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient_confirmations', to=settings.AUTH_USER_MODEL),
        ),
    ]
