# Generated by Django 4.0.2 on 2022-06-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_manager_base', '0015_alter_customusermodel_localization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['name'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
