# Generated by Django 4.0.2 on 2022-07-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_manager_base', '0017_alter_customusermodel_localization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='localization',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='warehouse_manager_base.localizationmodel'),
        ),
    ]
