# Generated by Django 4.0.2 on 2022-07-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_manager_base', '0018_customusermodel_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizationmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
